### ISSUE TITLE
Could this plugin be merged with OctoPrint-PauseForUserEvent

### ISSUE THREAD

**Issue by hakan42** [Patronics/OctoPrint-PrinterAlerts#2]
There is another plugin which has been just released:

https://github.com/zeroflow/OctoPrint-PauseForUserEvent

They seem to have the same purpose.

**Comment by Patronics** [comment]
Thanks for the suggestion, this plugin is indeed very similar to that one, but they do behave somewhat differently, as that one triggers events for other plugins to use, while this one provides an alert for the user. 
There are several other examples of similar plugins to each other that behave slightly differently, and are all available in the plugin repository. 
There's no reason not to install both plugins if you want both types of functionality, so I think it makes sense for them both to exist independently.
