### ISSUE TITLE
Python 3 Compatibility

### ISSUE THREAD

**Issue by ekr1** [Patronics/OctoPrint-PrinterAlerts#6]
Just FYI, this addon is flagged by the Python3 compatibility check in OctoPrint, and saw there has not been an issue regarding this before.

Thanks for the work you're investing!

**Comment by Patronics** [comment]
Yeah, thanks for letting me know! I've been busy with college classes until this week, so haven't had a chance to test this plugin with Python 3. I'll try it soon, and update as needed!

**Comment by cp2004** [comment]
@Patronics Doing the rounds on the plugin repo for those not yet Python 3 compatibility, your plugin passes the eye test for compatibility. If you would like, I can make a PR to add the few bits needed and fully test it. Let me know what you think.

**Comment by Patronics** [comment]
@cp2004 sorry for the late reply, I had some difficulties setting up a Python3 Octoprint environment for testing it with, if you'd be willing to test it and do a PR as necessary, that'd be great! Thanks in advance!

**Comment by cp2004** [comment]
No worries, I'll probably get on to it some point next week. Look out for a PR.

**Comment by ruedli** [comment]
@cp2004  & @Patronics Thanks for your work!

**Comment by cp2004** [comment]
@Patronics PR submitted, turns out it was compatible just needed the string.

**Comment by Patronics** [comment]
Awesome, thanks for testing it! Merged your PR 😃.
