### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by Deses** [Patronics/OctoPrint-PrinterAlerts#8]
Hi @Patronics!

Soon OctoPrint will drop support for Python 2, and I was wondering if or when you'll implement support for Python 3 so we can keep using your plugin.

Thanks!

**Comment by Patronics** [comment]
Thanks for the question! I actually had already implemented Python 3 support (see issue #6 ), but apparently had forgotten the step of marking a new release. It should properly detect that Python 3 is supported now, so I'll close this issue, but feel free to reopen it if it's still not working for you, or still showing up as incompatible.
